apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uskgnpiun-nodejs
  janus-idp.io/tekton: uskgnpiun-nodejs
  backstage.io/kubernetes-id: uskgnpiun-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uskgnpiun-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
