apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uskgnpiun-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6569dac049.qcb2.p3.openshiftapps.com/rhtap/rhtap-qe:76123817182aa612118fcd372721b1dfee710748@sha256:d606dc89c9cc804d353e3b824cb2b267a85d54c210444a49868b6d807f0bae44
          name: container-image
